### ISSUE TITLE
请问关于fbx原始材质的问题

### ISSUE THREAD

**Issue by novo2015** [ForeverZack/Unity-Gpu-Skinning-Tool#1]
你好，我使用你的代码生成了新的prefab，能够正常运行。 
有个问题想请问一下，fbx原来带的材质，上面有法线图等等。新生成的材质不带有这些信息。我把它原来的材质添加到新的prefab上，这时prefab上带了新生成的材质和原始的材质，出现了问题，原始的材质使得地面上躺着一个人，新的材质使得站着一个人在播放动作。 我应该怎么把它们控制的一致呢？新的prefab既有法线等信息，也能控制动作而不会出现两个人？
如果方便希望回复，或者发邮件novo2015@qq.com ，感谢~

**Comment by ForeverZack** [comment]
工程里用的shader只使用了mainTexture，只是为优化骨骼动画做的一个示例。具体最后显示的效果是需要根据自己根据需要处理的。你那边出现两个人，应该是同时给MeshRenderer拖进去2个材质，被渲染了两次

**Comment by ForeverZack** [comment]
> 你好，我使用你的代码生成了新的prefab，能够正常运行。
> 有个问题想请问一下，fbx原来带的材质，上面有法线图等等。新生成的材质不带有这些信息。我把它原来的材质添加到新的prefab上，这时prefab上带了新生成的材质和原始的材质，出现了问题，原始的材质使得地面上躺着一个人，新的材质使得站着一个人在播放动作。 我应该怎么把它们控制的一致呢？新的prefab既有法线等信息，也能控制动作而不会出现两个人？
> 如果方便希望回复，或者发邮件[novo2015@qq.com](mailto:novo2015@qq.com) ，感谢~

工程里用的shader只使用了mainTexture，只是为优化骨骼动画做的一个示例。具体最后显示的效果是需要根据自己根据需要处理的。你那边出现两个人，应该是同时给MeshRenderer拖进去2个材质，被渲染了两次

**Comment by novo2015** [comment]
嗯我是拖了两个材质。
如果需要既有原始材质的效果，又能控制动作，只能在生成新材质上增加原始材质的内容吗？
谢谢~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ForeverZack/Unity-Gpu-Skinning-Tool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月19日(星期二) 晚上6:13
收件人:&nbsp;"ForeverZack/Unity-Gpu-Skinning-Tool"<Unity-Gpu-Skinning-Tool@noreply.github.com&gt;;
抄送:&nbsp;"驱"<novo2015@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ForeverZack/Unity-Gpu-Skinning-Tool] 请问关于fbx原始材质的问题 (#1)





  
你好，我使用你的代码生成了新的prefab，能够正常运行。
 有个问题想请问一下，fbx原来带的材质，上面有法线图等等。新生成的材质不带有这些信息。我把它原来的材质添加到新的prefab上，这时prefab上带了新生成的材质和原始的材质，出现了问题，原始的材质使得地面上躺着一个人，新的材质使得站着一个人在播放动作。 我应该怎么把它们控制的一致呢？新的prefab既有法线等信息，也能控制动作而不会出现两个人？
 如果方便希望回复，或者发邮件novo2015@qq.com ，感谢~
  
工程里用的shader只使用了mainTexture，只是为优化骨骼动画做的一个示例。具体最后显示的效果是需要根据自己根据需要处理的。你那边出现两个人，应该是同时给MeshRenderer拖进去2个材质，被渲染了两次

**Comment by ForeverZack** [comment]
根据你想要的效果修改shader代码哦

**Comment by novo2015** [comment]
嗯嗯我试试，再次感谢
