### ISSUE TITLE
骨骼动画导出

### ISSUE THREAD

**Issue by baomakele** [ForeverZack/Unity-Gpu-Skinning-Tool#2]
你好大神，我这边使用学习了你这个插件，发现用骨骼导出的动画文件好像运行有点问题。望查看，非常感谢。

**Comment by ForeverZack** [comment]
啥问题

**Comment by baomakele** [comment]
我用你的工具导出骨骼动画信息，然后就会如图所示，更换_data 的动画文件就正常了，所以猜测导出骨骼的时候是不是哪里出现了小问题，谢谢回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ForeverZack/Unity-Gpu-Skinning-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月10日(星期三) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ForeverZack/Unity-Gpu-Skinning-Tool] 骨骼动画导出 (#2)





 
啥问题

**Comment by baomakele** [comment]
角色如果动态创建的话，播放动作会出现幻影

**Comment by ForeverZack** [comment]
不是很明白你说的幻影是什么，是表面顶点有波动吗？波动的话因为用2个RGBA去还原1个RGBAhalf的算法里小数位精度不够，要是用half的话，可以看看以前的版本

**Comment by ForeverZack** [comment]
当前的版本更适合导出顶点动画，如果要导出使用骨骼动画的话，参考下以前的版本修改一下数据纹理的格式以及shader里的还原算法

**Comment by baomakele** [comment]
嗯，我现在就是导出的顶点动画，您的这个工具做的非常不错，另外我可以添加您的联系方式，截取视频说明一下那个动态创建角色播放动画会出现幻影的问题吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ForeverZack/Unity-Gpu-Skinning-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月10日(星期三) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ForeverZack/Unity-Gpu-Skinning-Tool] 骨骼动画导出 (#2)





 
当前的版本更适合导出顶点动画，如果要导出使用骨骼动画的话，参考下以前的版本修改一下数据纹理的格式以及shader里的还原算法

**Comment by ForeverZack** [comment]
qq 472434835
