### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by machinetown44** [ForeverZack/Unity-Gpu-Skinning-Tool#5]
Hello, this is super useful and I'd like to be able to use it in my project, but there is no license specified. As much as I understand github terms, it means I technically can't use it without breaking copyright law. 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

A common open-source license on github is MIT, but if that wan't your intention to make it available for commercial use by default, perhaps we can come to some sort of agreement? I'm just a solo developer and it's for a game I want to eventually publish through steam.

**Comment by dobe0768** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ForeverZack** [comment]
Ok, I have upload MIT license. Just let me know when your game publish through steam. haha

**Comment by machinetown44** [comment]
Hey, that's awesome! 🤩
Thanks for the quick response! It'll probably be a while before it's finished, but feel free to shoot me an email at machinetown44@gmail.com so that I can send you a demo link once it's up. I'm hoping to have a vertical slice in a couple months.  

Thanks again, I'll close this issue as resolved now.

**Comment by ForeverZack** [comment]
Good luck!
